package me.gegenbauer.logviewer.strings

class StringsEn private constructor() {
    companion object {
        val STRINGS = listOf(
            "File"
            , "Open"
            , "Follow"
            , "Open files"
            , "Append files"
            , "Open Recents"
            , "Close"
            , "Exit"
            , "Setting"
            , "Adb"
            , "Font"
            , "Log"
            , "Start"
            , "Stop"
            , "Pause"
            , "Clear Views"
            , "Rotation"
            , "First"
            , "Last"
            , "Bold"
            , "Hide"
            , "Tag"
            , "PID"
            , "TID"
            , "Filter"
            , "Windowed Mode"
            , "View"
            , "Full Logs"
            , "Help"
            , "About"
            , "Bookmarks"
            , "Full"
            , "Incremental"
            , "Highlight"
            , "LogLevel"
            , "ScrollBack"
            , "Clear/Save"
            , "Log file"
            , "Connect"
            , "Refresh"
            , "Disconnect"
            , "Apply"
            , "ScrollBack(lines)"
            , "Split File"
            , "Color"
            , "Filters"
            , "Keep Log"
            , "OK"
            , "Cancel"
            , "New"
            , "Copy"
            , "Edit"
            , "Delete"
            , "Save"
            , "Select"
            , "Adb path"
            , "Log path"
            , "Size"
            , "Connected"
            , "Not connected"
            , "Append"
            , "Select file open mode"
            , "None"
            , "Add filter"
            , "Add cmd"
            , "Commands"
            , "Retry"
            , "Filter Style"
            , "Look and Feel"
            , "Full Log Table"
            , "Filter Log Table"
            , "Built-in schemes"
            , "Light"
            , "Dark"
            , "Appearance"
            , "Options"
            , "Log cmd"
            , "Not Found"
            , "Add Include"
            , "Add Exclude"
            , "Add Search"
            , "Set Search"
            , "Search"
            , "Cmd"
        )
    }
}
