name: Build macOS Artifacts
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.cpp'
      - '**.kt'
      - 'buildSrc/**'
      - 'gradle/**'
      - 'gradle.properties'
      - '**.kts'
      - '**.java'
      - '.github/workflows/build_macos_artifact.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.kt'
      - 'buildSrc/**'
      - 'gradle/**'
      - 'gradle.properties'
      - '**.kts'
      - '**.java'
  release:
    types:
      - published
jobs:
  macos:
    name: macOS (Java 17)
    runs-on: macos-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew packageReleaseDmg

      - name: Build UberJar
        run: ./gradlew packageReleaseUberJarForCurrentOS

      - name: Retrieve Artifact Name
        id: getJarFilename
        run: |
          find "$(pwd)/app/build/compose/jars" -type f -name "*.jar" -exec basename {} \;
          echo "::set-output name=jarFileName::$filename"

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v1
        with:
          name: catspy.jar
          path: app/build/compose/jars/${{ steps.getJarFilename.outputs.jarFileName }}
          retention-days: 1

      - name: Retrieve Artifact Name
        id: getDmgFilename
        run: |
          find "$(pwd)/app/build/compose/binaries/main-release/dmg" -type f -name "*.dmg" -exec basename {} \;
          echo "::set-output name=dmgFileName::$filename"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v1
        with:
          name: catspy_macos.dmg
          path: app/build/compose/binaries/main-release/dmg/${{ steps.getDmgFilename.outputs.dmgFileName }}
          retention-days: 1

