name: Release

on:
    push:
        tags:
            - '*'

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2

            - name: Build
              run: ./gradlew packageDeb

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload Linux Artifact
              id: upload_linux_artifact
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./app/build/compose/binaries/main/deb/catspy_amd64.deb
                  asset_name: catspy_amd64.deb
                  asset_content_type: application/octet-stream

    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2

            - name: Build
              run: ./gradlew packageMsi

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload Windows Artifact
              id: upload_windows_artifact
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./app/build/compose/binaries/main/msi/catspy_x64.msi
                  asset_name: catspy_x64.msi
                  asset_content_type: application/octet-stream